version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0
  jira: circleci/jira@1.3.1

jobs:
  build:
    working_directory: ~/public
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/copy:
          arguments: '--recursive'
          from: public
          to: 's3://connorglynn.com'

workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify