version: 2.1
jobs:
  build:
    working_directory: ~/public
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: install git
          command: apk update && apk add git
      - checkout