version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build:
    working_directory: ~/public
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/copy:
          arguments: '--recursive'
          from: public
          to: 's3://connorglynn.com'